os: linux # => 1
language: python # => 2
python: # => 3
  - "3.6"
env: # => 5
  -DJANGO=3.0 DB=sqlite
install: # => 6
  - pip install -r requirements.txt
  - pip install coveralls
# To run tests
script:
  - python STQA/manage.py test bmi_cal.tests
  - coverage run --source=STQA/bmi_cal STQA/manage.py test STQA/bmi_cal/tests/
# send coverage report to coveralls
after_success:
  coveralls
  

